import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = (process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL) as string;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY as string;

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing env vars');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: { persistSession: false },
});

const sql = `
-- Create posts table
create table if not exists posts (
  slug text primary key,
  title text not null,
  excerpt text,
  content_mdx text not null,
  category text,
  cover_url text,
  author text default 'Equipe OLV',
  published_at timestamptz default now(),
  status text default 'published'
);

-- Enable RLS
alter table posts enable row level security;

-- Create policy for public read access to published posts
create policy if not exists "public posts" on posts
  for select using (status = 'published');

-- Create ingest_logs table for monitoring
create table if not exists ingest_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  source text,
  rss_title text,
  parsing_status text,
  parsing_error text,
  exec_time_ms integer,
  status text,
  message text,
  stderr text
);

-- Enable RLS for ingest_logs
alter table ingest_logs enable row level security;

-- Create policy for admin access to ingest_logs
create policy if not exists "admin ingest_logs" on ingest_logs
  for all using (true);
`;

async function createTables() {
  try {
    console.log('Creating tables...');
    const { error } = await supabase.rpc('exec_sql', { sql });
    
    if (error) {
      console.error('Error creating tables:', error);
      // Try alternative method
      console.log('Trying alternative method...');
      const { error: error2 } = await supabase.from('posts').select('count').limit(1);
      if (error2 && error2.code === '42P01') {
        console.log('Tables do not exist. Please run the SQL manually in Supabase SQL Editor:');
        console.log(sql);
      }
    } else {
      console.log('Tables created successfully!');
    }
  } catch (err) {
    console.error('Error:', err);
    console.log('Please run this SQL manually in your Supabase SQL Editor:');
    console.log(sql);
  }
}

createTables(); 