-- ========================================
-- MIGRAÇÃO FINAL: Criação das tabelas do blog
-- ========================================

-- 1. Criação da tabela posts
create table if not exists posts (
  slug text primary key,
  title text not null,
  excerpt text,
  content_mdx text not null,
  category text,
  cover_url text,
  author text default 'Equipe OLV',
  published_at timestamptz default now(),
  status text default 'published',
  source_name text,
  source_url text
);

-- 2. Ativar Row Level Security (RLS) na tabela posts
alter table posts enable row level security;

-- 3. Remover policies antigas se existirem
drop policy if exists "public posts" on posts;

-- 4. Criar policy para leitura pública de posts publicados
create policy "public posts" on posts
  for select
  using (status = 'published');

-- 5. Criação da tabela ingest_logs
create table if not exists ingest_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  source text,
  rss_title text,
  parsing_status text,
  parsing_error text,
  exec_time_ms integer,
  status text,
  message text,
  stderr text,
  source_name text,
  source_url text
);

-- 6. Ativar RLS na tabela ingest_logs
alter table ingest_logs enable row level security;

-- 7. Remover policy antiga se existir
drop policy if exists "admin ingest_logs" on ingest_logs;

-- 8. Criar policy para acesso admin aos logs
create policy "admin ingest_logs" on ingest_logs
  for all using (true);

-- 9. Adicionar índices para performance
create index if not exists idx_posts_published_at on posts(published_at desc);
create index if not exists idx_posts_category on posts(category);
create index if not exists idx_posts_status on posts(status);
create index if not exists idx_ingest_logs_created_at on ingest_logs(created_at desc);
create index if not exists idx_ingest_logs_source on ingest_logs(source);

-- 10. Comentários para documentação
comment on table posts is 'Tabela de posts do blog com conteúdo gerado automaticamente';
comment on table ingest_logs is 'Logs de ingestão automática de feeds RSS';
comment on column posts.source_name is 'Nome da fonte original do artigo';
comment on column posts.source_url is 'URL original do artigo na fonte'; 